services:
  accounts:
    image: "ikucuk/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ikucuk-banking-network
  cards:
    image: "ikucuk/cards:s4"
    container_name: cards-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ikucuk-banking-network
  loans:
    image: "ikucuk/loans:s4"
    container_name: loans-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ikucuk-banking-network
networks :
  ikucuk-banking-network:
    driver: "bridge"
